spark.master                           spark://spark-master:7077
spark.eventLog.enabled                 true
spark.eventLog.dir                   hdfs://namenode:9000/spark-events
spark.history.fs.logDirectory        hdfs://namenode:9000/spark-events
spark.hadoop.fs.defaultFS            hdfs://namenode:9000
spark.hadoop.hive.metastore.uris      thrift://hive-server:10002
spark.sql.warehouse.dir                /user/hive/warehouse
# JDBC vers Metastore PostgreSQL
spark.hadoop.javax.jdo.option.ConnectionURL=jdbc:postgresql://hive-metastore-postgres:5432/metastore
spark.hadoop.javax.jdo.option.ConnectionDriverName=org.postgresql.Driver
spark.hadoop.javax.jdo.option.ConnectionUserName=hiveuser
spark.hadoop.javax.jdo.option.ConnectionPassword=hivepassword

# S'assurer que Hive est bien utilisé
spark.sql.catalogImplementation=hive

# Limites ressources pour éviter crash executors
spark.executor.memory                  4g
spark.driver.memory                    4g
spark.executor.cores                   2
spark.task.cpus                       2
