# Generated by Django 5.2.4 on 2025-08-02 15:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jeu',
            fields=[
                ('id_jeu', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('est_actif', models.BooleanField(default=True)),
                ('regles', models.TextField(blank=True, null=True)),
                ('recompenses', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Jeu',
                'verbose_name_plural': 'Jeux',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id_offre', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('type_offre', models.CharField(choices=[('ACHAT', 'Achat de forfait'), ('RECHARGE', 'Recharge de crédit'), ('PROMO', 'Offre promotionnelle')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('duree_validite', models.IntegerField(help_text='Durée de validité en jours')),
                ('data_incluse', models.FloatField(default=0, help_text='Quantité de données en Mo')),
                ('appels_inclus', models.IntegerField(default=0, help_text='Durée des appels en minutes')),
                ('sms_inclus', models.IntegerField(default=0)),
                ('est_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Offre',
                'verbose_name_plural': 'Offres',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_activite', models.DateTimeField(auto_now=True)),
                ('segment', models.CharField(choices=[('PREPAYE', 'Prépayé'), ('POSTPAYE', 'Postpayé'), ('MIXTE', 'Mixte')], default='PREPAYE', max_length=20)),
                ('niveau_fidelite', models.CharField(choices=[('NOUVEAU', 'Nouveau client'), ('REGULIER', 'Client régulier'), ('FIDELE', 'Client fidèle'), ('VIP', 'Client VIP')], default='NOUVEAU', max_length=20)),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('est_actif', models.BooleanField(default=True)),
                ('donnees_consentement', models.JSONField(blank=True, help_text='Préférences de communication et consentements', null=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-date_inscription'],
                'indexes': [models.Index(fields=['telephone'], name='marketing_d_telepho_9cacbd_idx'), models.Index(fields=['segment'], name='marketing_d_segment_4ae7b6_idx'), models.Index(fields=['niveau_fidelite'], name='marketing_d_niveau__dbb076_idx')],
            },
        ),
        migrations.CreateModel(
            name='Consommation',
            fields=[
                ('id_consommation', models.AutoField(primary_key=True, serialize=False)),
                ('type_consommation', models.CharField(choices=[('DATA', 'Données mobiles'), ('VOIX', 'Appels vocaux'), ('SMS', 'Messagerie SMS')], max_length=20)),
                ('quantite', models.FloatField(help_text='Quantité consommée (Mo pour data, minutes pour voix, nombre pour SMS)')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('montant_facture', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consommations', to='marketing_dashboard.client')),
                ('forfait_associe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing_dashboard.offre')),
            ],
            options={
                'verbose_name': 'Consommation',
                'verbose_name_plural': 'Consommations',
                'ordering': ['-date_debut'],
                'indexes': [models.Index(fields=['client'], name='marketing_d_client__b5dd34_idx'), models.Index(fields=['type_consommation'], name='marketing_d_type_co_924588_idx'), models.Index(fields=['date_debut', 'date_fin'], name='marketing_d_date_de_1fb7e5_idx')],
            },
        ),
        migrations.CreateModel(
            name='ParticipationJeu',
            fields=[
                ('id_participation', models.AutoField(primary_key=True, serialize=False)),
                ('date_participation', models.DateTimeField(default=django.utils.timezone.now)),
                ('gagnant', models.BooleanField(default=False)),
                ('montant_gagne', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('details', models.JSONField(blank=True, help_text='Détails de la participation', null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations_jeu', to='marketing_dashboard.client')),
                ('jeu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='marketing_dashboard.jeu')),
            ],
            options={
                'verbose_name': 'Participation à un jeu',
                'verbose_name_plural': 'Participations aux jeux',
                'ordering': ['-date_participation'],
                'indexes': [models.Index(fields=['jeu'], name='marketing_d_jeu_id_d58804_idx'), models.Index(fields=['client'], name='marketing_d_client__87320b_idx'), models.Index(fields=['gagnant'], name='marketing_d_gagnant_ff140d_idx')],
                'unique_together': {('jeu', 'client')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id_transaction', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type_transaction', models.CharField(choices=[('ACHAT', 'Achat de forfait'), ('RECHARGE', 'Recharge de crédit')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('source', models.CharField(choices=[('USSD', 'USSD'), ('APP', 'Application Mobile'), ('BOUTIQUE', 'Boutique physique'), ('SITE', 'Site Web'), ('AUTRE', 'Autre')], max_length=20)),
                ('date_transaction', models.DateTimeField(default=django.utils.timezone.now)),
                ('etat', models.CharField(choices=[('REUSSIE', 'Réussie'), ('ECHOUEE', 'Échouée'), ('EN_COURS', 'En cours'), ('ANNULEE', 'Annulée')], default='REUSSIE', max_length=20)),
                ('details', models.JSONField(blank=True, help_text='Détails supplémentaires de la transaction', null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='marketing_dashboard.client')),
                ('offre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing_dashboard.offre')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date_transaction'],
                'indexes': [models.Index(fields=['date_transaction'], name='marketing_d_date_tr_c05d48_idx'), models.Index(fields=['client'], name='marketing_d_client__b98e40_idx'), models.Index(fields=['offre'], name='marketing_d_offre_i_d1e8cd_idx'), models.Index(fields=['type_transaction'], name='marketing_d_type_tr_9c1727_idx')],
            },
        ),
    ]
