# Generated by Django 5.2.4 on 2025-07-11 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('batch', 'Batch'), ('streaming', 'Streaming')], max_length=10)),
                ('status', models.CharField(max_length=20)),
                ('logs', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('batch', 'Batch'), ('streaming', 'Streaming')], max_length=10)),
                ('cron_expression', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('records_processed', models.IntegerField()),
                ('processing_time', models.FloatField()),
                ('error_count', models.IntegerField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.jobhistory')),
            ],
        ),
    ]
